using Xunit.Abstractions;

namespace PastyPropellant.PropellantStructure.Tests;

/// <summary>
/// Tests of the reference apparatus itself, not of the port.
/// </summary>
/// <remarks>
/// A golden-master suite is only as good as its claim that each fixture's input is
/// the input that produced its output. That claim rests on one flag,
/// <c>agrees_with_m</c>, generated by <c>reference/propstruct/parse_runs.py</c> —
/// and the flag was incomplete: <c>check_dat_against_m</c> compares each fraction's
/// size bounds and never its mass share. These tests pin what the completed check
/// found, so a regenerated <c>runs.json</c> cannot quietly reintroduce it.
/// </remarks>
public sealed class ReferenceRunsTests(ITestOutputHelper output)
{
    /// <summary>
    /// Every run the L2 theories replay must have an input the port can be held to.
    /// </summary>
    /// <remarks>
    /// A <see cref="FactAttribute"/> over the whole list rather than a theory on it,
    /// because a theory keyed on <see cref="ArchivedRunFixture.ReplayableRuns"/> is
    /// what <c>ProtocolTests</c> reads as "this replays an archived run" — and this
    /// one only reads the metadata.
    /// </remarks>
    [Fact]
    public void EveryReplayedRunStillHasItsOwnInput()
    {
        var without = ArchivedRunFixture.ReplayableRuns
            .Cast<object[]>()
            .Select(row => (string)row[0])
            .Where(id => !ReferenceRuns.ById(id).HasExactInput)
            .ToArray();

        Assert.True(
            without.Length == 0,
            $"replayed by the L2 theories but the .dat no longer describes them: {string.Join(", ", without)}");
    }

    /// <summary>
    /// <c>hp90</c>'s input file carries <c>hp95</c>'s recipe, and the archive's own
    /// flag does not notice.
    /// </summary>
    /// <remarks>
    /// The two runs share <c>HPEPA10.dat</c>, which kept only its last state. They
    /// also share all three size bounds (10-50, 113-180, 160-315 µm), which is why
    /// the bounds-only check passed the file. What differs is the split between the
    /// first two fractions — the whole point of the sweep the two runs belong to.
    /// </remarks>
    [Fact]
    public void TheHp90InputFileIsAlaterRevision()
    {
        var run = ReferenceRuns.ById("hp90");
        var file = Assert.IsType<ReferenceInputFile>(run.InputDat);

        Assert.Equal("HPEPA10.dat", file.ArchiveFile);

        // The bounds agree - this is what the archive's own check looks at.
        Assert.Equal(run.Fractions.Count, file.Fractions.Count);
        for (var index = 0; index < run.Fractions.Count; index++)
        {
            // Relative, because the report rounds a bound to single precision:
            // 5.0e-5 m is echoed as 4.9999999e-05.
            Assert.Equal(1.0, file.Fractions[index].MinSizeMetres / run.Fractions[index].MinSizeMetres, 6);
            Assert.Equal(1.0, file.Fractions[index].MaxSizeMetres / run.Fractions[index].MaxSizeMetres, 6);
        }

        // The shares do not: the report echoes 0.463/0.0514 and the file holds
        // 0.4883/0.0257, which is hp95.
        Assert.False(run.HasExactInput, "hp90's .dat holds hp95's shares; the run has no exact input.");

        output.WriteLine($"report  {string.Join(" ", run.Fractions.Select(f => f.MassFraction.ToString("0.####")))}");
        output.WriteLine($"file    {string.Join(" ", file.Fractions.Select(f => f.MassFraction.ToString("0.####")))}");
    }

    /// <summary>
    /// Re-checking the shares moves exactly one run, and it is <c>hp90</c>.
    /// </summary>
    /// <remarks>
    /// Fourteen of the forty-three files disagree with their report on mass shares.
    /// Thirteen were already flagged, because their size bounds drifted as well —
    /// so completing the check cannot silently shrink the reference set. If this
    /// count ever moves, the archive changed, not the port.
    /// </remarks>
    [Fact]
    public void CompletingTheCheckDisqualifiesOnlyHp90()
    {
        var disqualified = ReferenceRuns.All
            .Where(run => run.InputDat is { FlaggedAgreement: true, SharesMatchReport: false })
            .Select(run => run.Id)
            .ToArray();

        output.WriteLine($"exact inputs after the check: {ReferenceRuns.All.Count(r => r.HasExactInput)}");
        Assert.Equal(["hp90"], disqualified);
    }
}
