//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParametricCombustionModel.ReportMaking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CombustionSolverParamsReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CombustionSolverParamsReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParametricCombustionModel.ReportMaking.Resources.CombustionSolverParamsReportReso" +
                            "urces", typeof(CombustionSolverParamsReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предэкспонентный коэффициент реакций в конденсированной фазе {0}.
        /// </summary>
        internal static string ADecompose {
            get {
                return ResourceManager.GetString("ADecompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предэкспонентный коэффициент реакций в газовой фазе в пределах МКМ {0}.
        /// </summary>
        internal static string AKineticFlameInterPocket {
            get {
                return ResourceManager.GetString("AKineticFlameInterPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предэкспонентный коэффициент реакций в газовой фазе в пределах «кармана» вне КС {0}.
        /// </summary>
        internal static string AKineticFlamePocketOutSkeleton {
            get {
                return ResourceManager.GetString("AKineticFlamePocketOutSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предэкспонентный коэффициент реакций в газовой фазе в пределах КС {0}.
        /// </summary>
        internal static string AKineticFlamePocketSkeleton {
            get {
                return ResourceManager.GetString("AKineticFlamePocketSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разность удельной теплоты испарения и разложения связующего {0}.
        /// </summary>
        internal static string DeltaH {
            get {
                return ResourceManager.GetString("DeltaH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия активации реакций в конденсированной фазе {0}.
        /// </summary>
        internal static string EDecompose {
            get {
                return ResourceManager.GetString("EDecompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия активации реакций в газовой фазе в пределах МКМ {0}.
        /// </summary>
        internal static string EKineticFlameInterPocket {
            get {
                return ResourceManager.GetString("EKineticFlameInterPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия активации реакций в газовой фазе в пределах «кармана» вне КС {0}.
        /// </summary>
        internal static string EKineticFlamePocketOutSkeleton {
            get {
                return ResourceManager.GetString("EKineticFlamePocketOutSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия активации реакций в газовой фазе в пределах КС {0}.
        /// </summary>
        internal static string EKineticFlamePocketSkeleton {
            get {
                return ResourceManager.GetString("EKineticFlamePocketSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия активации реакций, обусловленных сгоранием металла в КС, {0}.
        /// </summary>
        internal static string EMetalBurning {
            get {
                return ResourceManager.GetString("EMetalBurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оптимизируемые параметры.
        /// </summary>
        internal static string HeaderOfCombustionSolverParams {
            get {
                return ResourceManager.GetString("HeaderOfCombustionSolverParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постоянный коэффициент в выражении для плотности теплового потока, обусловленного сгоранием металла в КС, {0}.
        /// </summary>
        internal static string HMetalBurning {
            get {
                return ResourceManager.GetString("HMetalBurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постоянный коэффициент высоты диффузионного пламени {0:0.0000}.
        /// </summary>
        internal static string KDiffusionHeight {
            get {
                return ResourceManager.GetString("KDiffusionHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок химических реакций в газовой фазе {0}.
        /// </summary>
        internal static string Nu {
            get {
                return ResourceManager.GetString("Nu", resourceCulture);
            }
        }
    }
}
