//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParametricCombustionModel.ReportMaking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstraintPenaltyEvaluatorReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstraintPenaltyEvaluatorReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParametricCombustionModel.ReportMaking.Resources.ConstraintPenaltyEvaluatorReport" +
                            "Resources", typeof(ConstraintPenaltyEvaluatorReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональные ограничения.
        /// </summary>
        internal static string HeaderOfConstraintPenaltyEvaluators {
            get {
                return ResourceManager.GetString("HeaderOfConstraintPenaltyEvaluators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное отношение плотностей тепловых потоков (max/min) {0:0.00}.
        /// </summary>
        internal static string HeatFluxRatioThreshold {
            get {
                return ResourceManager.GetString("HeatFluxRatioThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линейная скорость горения первого условного топлива больше, чем у второго..
        /// </summary>
        internal static string InterPocketFasterBurnPenaltyEvaluator {
            get {
                return ResourceManager.GetString("InterPocketFasterBurnPenaltyEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ограничение на максимальную плотность тепловых потоков кинетических пламен..
        /// </summary>
        internal static string KineticFlameHeatFluxPenaltyEvaluator {
            get {
                return ResourceManager.GetString("KineticFlameHeatFluxPenaltyEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная плотность теплового потока кинетического пламени в МКМ {0:0.00e+00}.
        /// </summary>
        internal static string MaxInterPocketKineticFlameHeatFlux {
            get {
                return ResourceManager.GetString("MaxInterPocketKineticFlameHeatFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная плотность теплового потока кинетического пламени в пределах «кармана» вне КС {0:0.00e+00}.
        /// </summary>
        internal static string MaxOutSkeletonKineticFlameHeatFlux {
            get {
                return ResourceManager.GetString("MaxOutSkeletonKineticFlameHeatFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная плотность теплового потока кинетического пламени в пределах КС {0:0.00e+00}.
        /// </summary>
        internal static string MaxSkeletonKineticFlameHeatFlux {
            get {
                return ResourceManager.GetString("MaxSkeletonKineticFlameHeatFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постоянный коэффициент «штрафа» {0:0.0000}.
        /// </summary>
        internal static string PenaltyRate {
            get {
                return ResourceManager.GetString("PenaltyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие реализации конкуренции пламен в пределах «кармана»..
        /// </summary>
        internal static string PocketHeatFluxRatioCompetitionPenaltyEvaluator {
            get {
                return ResourceManager.GetString("PocketHeatFluxRatioCompetitionPenaltyEvaluator", resourceCulture);
            }
        }
    }
}
