using System.Numerics;
using UnitsNet;

namespace ParametricCombustionModel.Computation.Units;

/// <summary>
/// Enum representing the unit of the metal burning coefficient, currently supporting Watts per Kelvin per square meter.
/// </summary>
public enum MetalBurningCoefficientUnit
{
    /// <summary>
    /// Unit representing Watts per Kelvin per square meter.
    /// </summary>
    WattsPerKelvinPerSquareMeter
}

/// <summary>
/// Struct representing the metal burning coefficient, used to model heat flux generated by metal combustion.
/// This coefficient is typically used in computational models to understand the thermal behavior of burning metals.
/// </summary>
public readonly struct HMetalBurningCoefficient
    : IMultiplyOperators<HMetalBurningCoefficient, Temperature, HeatFlux>,
      IMultiplyOperators<HMetalBurningCoefficient, double, HMetalBurningCoefficient>
{
#region Fields

    /// <summary>
    /// The numeric value of the metal burning coefficient.
    /// </summary>
    private readonly double _value;

    /// <summary>
    /// The unit of the metal burning coefficient, currently only supporting Watts per Kelvin per square meter.
    /// </summary>
    private readonly MetalBurningCoefficientUnit? _unit;

#endregion

#region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="HMetalBurningCoefficient"/> struct with a specified value and unit.
    /// </summary>
    /// <param name="value">The numeric value of the metal burning coefficient.</param>
    /// <param name="unit">The unit of the metal burning coefficient.</param>
    public HMetalBurningCoefficient(
        double value,
        MetalBurningCoefficientUnit unit)
    {
        _value = value;
        _unit = unit;
    }

#endregion

#region Properties

    /// <summary>
    /// Gets the value of the metal burning coefficient in Watts per Kelvin per square meter.
    /// </summary>
    /// <exception cref="NotImplementedException">
    /// Thrown when the unit of the metal burning coefficient is not supported.
    /// </exception>
    public double WattsPerKelvinPerSquareMeter =>
        _unit switch
        {
            MetalBurningCoefficientUnit.WattsPerKelvinPerSquareMeter => _value,
            _ => throw new NotImplementedException()
        };

#endregion

#region Operators

    /// <summary>
    /// Multiplies the metal burning coefficient by a temperature to produce a heat flux.
    /// </summary>
    /// <param name="left">The metal burning coefficient.</param>
    /// <param name="right">The temperature.</param>
    /// <returns>
    /// The resulting heat flux, calculated by multiplying the metal burning coefficient by the temperature.
    /// </returns>
    public static HeatFlux operator *(
        HMetalBurningCoefficient left,
        Temperature right)
    {
        return HeatFlux.FromWattsPerSquareMeter(
            left.WattsPerKelvinPerSquareMeter * right.Kelvins);
    }

    /// <summary>
    /// Multiplies the metal burning coefficient by a scalar value to produce a scaled metal burning coefficient.
    /// </summary>
    /// <param name="left">The metal burning coefficient.</param>
    /// <param name="right">The scalar value to multiply by.</param>
    /// <returns>
    /// The resulting metal burning coefficient after scaling by the specified scalar value.
    /// </returns>
    public static HMetalBurningCoefficient operator *(
        HMetalBurningCoefficient left,
        double right)
    {
        return FromWattsPerKelvinPerSquareMeter(
            left.WattsPerKelvinPerSquareMeter * right);
    }

#endregion

#region Methods

    /// <summary>
    /// Creates a new instance of <see cref="HMetalBurningCoefficient"/> with a value in Watts per Kelvin per square meter.
    /// </summary>
    /// <param name="value">The value in Watts per Kelvin per square meter.</param>
    /// <returns>A new instance of <see cref="HMetalBurningCoefficient"/>.</returns>
    public static HMetalBurningCoefficient FromWattsPerKelvinPerSquareMeter(
        double value)
    {
        return new HMetalBurningCoefficient(value, MetalBurningCoefficientUnit.WattsPerKelvinPerSquareMeter);
    }

    public override string ToString()
    {
        return $"{_value:0.00e+00} W/(K·m²)";
    }

#endregion
}
