<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="../../../Common/src/PastyPropellant.Core/PastyPropellant.Core.csproj" />
      <ProjectReference Include="..\ParametricCombustionModel.Computation\ParametricCombustionModel.Computation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetDifferentialEvolution" Version="4.0.0" />
      <PackageReference Include="DotNetNelderMead" Version="1.0.0" />
      <PackageReference Include="DotNetNelderMead.DifferentialEvolution" Version="1.0.0" />
    </ItemGroup>

</Project>
