using System.Collections.ObjectModel;
using System.Text.Json;
using ParametricCombustionModel.Core.Models;
using ParametricCombustionModel.PdfReportMaking.Builders;
using ParametricCombustionModel.PdfReportMaking.Enums;
using ParametricCombustionModel.PdfReportMaking.Models;
using ParametricCombustionModel.PlotRenderer.Models;
using ParametricCombustionModel.PlotRenderer.Renderers;
using ParametricCombustionModel.ReportMaking.Models;
using ParametricCombustionModel.ReportMaking.ReportMakers;
using PastyPropellant.Core.Utils;

namespace ParametricCombustionModel.ProcessWorker.Scenarios;

public static class ReportPdfPrintScenario
{
    public static void GetPrintedReport(IEnumerable<string> titleLines,
                                        IEnumerable<double> point,
                                        IEnumerable<double> pressuresForReport,
                                        IEnumerable<double> pressuresForTargetFunction,
                                        string outputFile,
                                        string propellantsFilePath)
    {
        var propellants = GetPropellants(propellantsFilePath);
        var report = GetReport(point, pressuresForReport, pressuresForTargetFunction, propellants);

        var plotReport = GetReport(point, pressuresForTargetFunction, pressuresForTargetFunction, propellants);
        PrintBurningRatesPlot(plotReport);
        PrintPocketSurfaceFractionsPlot(plotReport);

        var reportMaker = PdfReportMakerBuilder.FromReport(report)
                                               .WithFileName(outputFile)
                                               .WithTitle(titleLines.Select(
                                                              line => new PdfLine(LineStyle.Underline, line)))
                                               .WithFooter(GetPdfFooterLines(point))
                                               .Build();

        var operationResult = reportMaker.Generate();
        if (operationResult.IsSuccess == false)
            EventBus<string>.Publish(operationResult.Exception!.ToString());
    }

    private static void PrintBurningRatesPlot(Report report)
    {
        var settings = new PlotSettings
        {
            Title = "Burning Rates",
            XAxisMinimum = 0.9e6,
            XAxisMaximum = 6.6e6,
            XAxisTitle = "Pressure, Pa",
            YAxisTitle = "mm/s"
        };
        var plotRenderer = new BurningRatePlotRenderer();
        plotRenderer.Render(report, settings);
    }

    private static void PrintPocketSurfaceFractionsPlot(Report report)
    {
        var settings = new PlotSettings
        {
            Title = "Pocket Surface Fractions",
            XAxisMinimum = 0.9e6,
            XAxisMaximum = 6.6e6,
            XAxisTitle = "Pressure, Pa",
            YAxisTitle = string.Empty
        };
        var plotRenderer = new PocketSurfaceFractionPlotRenderer();
        plotRenderer.Render(report, settings);
    }

    private static IEnumerable<PdfLine> GetPdfFooterLines(IEnumerable<double> point)
    {
        return
        [
            new PdfLine(LineStyle.None, $"Actual time: {DateTime.Now}"),
            new PdfLine(LineStyle.None, JsonSerializer.Serialize(point.ToArray()).Replace(",", ", ")),
            new PdfLine(LineStyle.None, "Generated by ParametricCombustionModel")
        ];
    }

    private static ReadOnlyCollection<Propellant> GetPropellants(string filePath)
    {
        using FileStream fileStream = new(filePath, FileMode.Open, FileAccess.Read, FileShare.Read);
        var result = JsonSerializer.DeserializeAsync<List<Propellant>>(fileStream).Result;
        return result!.AsReadOnly();
    }

    private static Report GetReport(IEnumerable<double> point,
                                    IEnumerable<double> pressuresForReport,
                                    IEnumerable<double> pressuresForTargetFunction,
                                    ReadOnlyCollection<Propellant> propellants)
    {
        var context = new ReportMakingContext(propellants.AsReadOnly(),
                                              point.ToArray().AsReadOnly(),
                                              pressuresForReport.ToArray().AsReadOnly(),
                                              pressuresForTargetFunction.ToArray().AsReadOnly());
        return ReportMaker.GetReport(context).Value!;
    }
}
